export const categories = ["All", "Silk", "Cotton", "Linen", "Ikat", "Tweed & Herringbone", "Garments"] as const;
export type Category = typeof categories[number];

export interface Product {
    id: number;
    name: string;
    subtitle: string;
    category: Category;
    tag: string;
    description: string;
    img: string;
    origin: string;
    useCase: string[];
    highlight: string;
}

export const products: Product[] = [
    {
        id: 1,
        name: "Katan Silk",
        subtitle: "Pure twisted warp",
        category: "Silk",
        tag: "Flagship",
        description: "Woven from pure twisted silk yarns, Katan is the jewel of Varanasi. Tight weave, brilliant drape, and a surface that catches light the way no synthetic can replicate.",
        img: "/images/fabric/silk.jpeg",
        origin: "Varanasi, UP",
        useCase: ["Bridal wear", "Sarees", "Couture"],
        highlight: "GI-tagged Banarasi",
    },
    {
        id: 2,
        name: "Tussar Silk",
        subtitle: "Wild-silk texture",
        category: "Silk",
        tag: "Natural",
        description: "Harvested from wild silkworms, Tussar carries an organic texture and muted sheen that refined cultivated silk cannot match. Preferred by designers who want substance with soul.",
        img: "/images/fabric/silk.jpeg",
        origin: "Varanasi, UP",
        useCase: ["Kurtas", "Stoles", "Home linen"],
        highlight: "Wild-harvested yarn",
    },
    {
        id: 3,
        name: "Premium Cotton",
        subtitle: "Long-staple softness",
        category: "Cotton",
        tag: "Bestseller",
        description: "Long-staple cotton from certified mills, woven to a 200–400 thread count finish. Soft, breathable, and durable — suitable for everyday garments and upholstery alike.",
        img: "/images/fabric/cotton.jpeg",
        origin: "Varanasi & Gujarat",
        useCase: ["Apparel", "Bed linen", "Uniforms"],
        highlight: "400 thread count",
    },
    {
        id: 4,
        name: "Cotton Dobby",
        subtitle: "Surface texture weave",
        category: "Cotton",
        tag: "Textured",
        description: "Woven on dobby looms, these cottons carry a raised geometric surface that adds dimension to otherwise plain cloth. Popular with European fashion labels for shirting.",
        img: "/images/fabric/cotton.jpeg",
        origin: "Varanasi, UP",
        useCase: ["Shirting", "Trousers", "Furnishing"],
        highlight: "Dobby construction",
    },
    {
        id: 5,
        name: "European Linen",
        subtitle: "Natural fibre elegance",
        category: "Linen",
        tag: "Export Grade",
        description: "Crisp, breathable linen woven to international standards. The natural slub texture is preserved in our finishing process, giving the cloth its characteristic honest feel.",
        img: "/images/fabric/linen.jpeg",
        origin: "Varanasi (processed)",
        useCase: ["Interiors", "Resort wear", "Tablecloths"],
        highlight: "Zero synthetic blend",
    },
    {
        id: 6,
        name: "Linen-Cotton Blend",
        subtitle: "Comfort meets structure",
        category: "Linen",
        tag: "Versatile",
        description: "The ease of cotton woven together with the structure of linen. This blend is our most versatile fabric — travelling equally well into wardrobe and interior applications.",
        img: "/images/fabric/linen.jpeg",
        origin: "Varanasi, UP",
        useCase: ["Jackets", "Cushions", "Dresses"],
        highlight: "55/45 blend ratio",
    },
    {
        id: 7,
        name: "Warp-Ikat",
        subtitle: "Resist-dyed yarns",
        category: "Ikat",
        tag: "Artisan",
        description: "The warp yarns are resist-dyed before weaving, creating the characteristic soft-edged, blurred patterns that make Ikat instantly recognisable. Each piece is unique by definition.",
        img: "/images/fabric/ikat.jpeg",
        origin: "Varanasi & Pochampally",
        useCase: ["Statement apparel", "Art pieces", "Wall hangings"],
        highlight: "Hand-dyed warp",
    },
    {
        id: 8,
        name: "Double Ikat",
        subtitle: "Both warp and weft",
        category: "Ikat",
        tag: "Rare",
        description: "Among the most technically demanding weaves in India — both warp and weft yarns are resist-dyed and aligned perfectly before weaving. Fewer than a dozen workshops can do this well.",
        img: "/images/fabric/ikat.jpeg",
        origin: "Patan & Varanasi",
        useCase: ["Collector pieces", "Luxury fashion", "Heritage sarees"],
        highlight: "Dual-axis resist dyeing",
    },
    {
        id: 9,
        name: "Herringbone Suiting",
        subtitle: "Classic zig-zag construction",
        category: "Tweed & Herringbone",
        tag: "Classic",
        description: "The timeless V-pattern woven in fine wool-blend yarn. Structured, crisp, and eternally relevant. Widely exported to the UK and European suiting markets.",
        img: "/images/fabric/herring.jpeg",
        origin: "Varanasi, UP",
        useCase: ["Suits", "Blazers", "Coats"],
        highlight: "Wool-blend construction",
    },
    {
        id: 10,
        name: "Upholstery Tweed",
        subtitle: "Dense woven durability",
        category: "Tweed & Herringbone",
        tag: "Commercial",
        description: "Heavy-weight tweed constructed for upholstery applications. Resistant to abrasion, colourfast under UV, and available in a library of heathered tones.",
        img: "/images/fabric/tweed.jpeg",
        origin: "Varanasi, UP",
        useCase: ["Furniture", "Automotive", "Hospitality"],
        highlight: "350 GSM construction",
    },
    {
        id: 11,
        name: "Silk Kurtas",
        subtitle: "Ready-to-wear artisan",
        category: "Garments",
        tag: "Clothing",
        description: "Crafted in our in-house garment unit from our own Katan and Tussar silks. Each kurta is cut by hand and stitched to bespoke measurements for boutique labels.",
        img: "/images/fabric/silk.jpeg",
        origin: "Varanasi factory",
        useCase: ["Boutique retail", "Export", "Private label"],
        highlight: "Bespoke cut & sew",
    },
    {
        id: 12,
        name: "Linen Separates",
        subtitle: "Resort & casual wear",
        category: "Garments",
        tag: "Clothing",
        description: "A growing line of unisex linen separates — shirts, trousers, and kaftans — designed for our export partners in Europe and the Middle East.",
        img: "/images/fabric/linen.jpeg",
        origin: "Varanasi factory",
        useCase: ["Resort wear", "Wholesale", "Private label"],
        highlight: "GOTS-compliant fabric",
    },
];